// Generated by nuxt-laravel-echo module
import type { EchoAppConfig } from '/Users/truonggiangnguyenkhoa/code/brezze_app/vusticFE/node_modules/.pnpm/nuxt-laravel-echo@0.2.7_socket.io-client@4.8.1/node_modules/nuxt-laravel-echo/dist/runtime/types/config.ts';

declare module 'nuxt/schema' {
    interface AppConfig {
        echo?: EchoAppConfig;
    }
    interface AppConfigInput {
        echo?: EchoAppConfig;
    }
}

declare module '@nuxt/schema' {
    interface AppConfig {
        echo?: EchoAppConfig;
    }
    interface AppConfigInput {
        echo?: EchoAppConfig;
    }
}

export {};